[package]
name = "skia-safe"

description = "Safe Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
# 5 max
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
# 6 max
categories = ["api-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"] 
license = "MIT"

version = "0.26.1"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[lib]
doctest = false

[features]
default = []
gl = ["gpu", "skia-bindings/gl"]
vulkan = ["gpu", "skia-bindings/vulkan"]
metal = ["gpu", "skia-bindings/metal"]
textlayout = ["skia-bindings/textlayout"]
# implied only, do not use
gpu = []
# deprecated since 0.25.0, forwarded to skia-bindings with the intend to print some warnings while build.rs is running
svg = ["skia-bindings/svg"]
shaper = ["textlayout", "skia-bindings/shaper"]

[dependencies]
bitflags = "1.0.4"
skia-bindings = { version = "=0.26.1", path = "../skia-bindings" }
lazy_static = "1.4"

[dev-dependencies]
serial_test = "0.3"
serial_test_derive = "0.4"
