[package]
name = "skia-safe"

description = "Safe Skia Bindings for Rust"
homepage = "https://github.com/rust-skia/rust-skia"
repository = "https://github.com/rust-skia/rust-skia"
readme = "README.md"
# 5 max
keywords = ["skia", "rust-bindings", "vulkan", "opengl", "pdf"]
# 6 max
categories = ["api-bindings", "graphics", "multimedia::images", "rendering::graphics-api", "visualization"] 
license = "MIT"

version = "0.18.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[features]
default = ["vulkan"]
vulkan = ["skia-bindings/vulkan"]
svg = ["skia-bindings/svg"]
shaper = ["skia-bindings/shaper"]
textlayout = ["skia-bindings/textlayout", "shaper"]

[dependencies]
bitflags = "1.0.4"
skia-bindings = { version = "=0.18.0", path = "../skia-bindings" }
lazy_static = "1.4"

[dev-dependencies]
# for skia-org
offscreen_gl_context = "0.25.0"
# for offscreen_gl_context 0.25
sparkle = "0.1.4"
clap = "2.33.0"
ash = "0.29"
