#!/usr/bin/env python3
"""Touch-point scan for the Type Bindings Table (ADR 0001).

For every `Include` entry in type_bindings.rs, searches the Rust code
(`skia-safe/src`, `skia-bindings/src`) and classifies two usage properties
independently:

  fields-used   — the type's *members* are read or written:
                    field access      `<Type>.<field>`
                    struct literal    `<Type> { .. }`
                    transmutable      `native_transmutable!(... Type ...)`
                    wrapper chain     `native()/native_mut().<field>`

  function-used — the type appears in a *call position* only:
                    `C_<Name>_(...)` wrappers, `<Type>::method(..)`

  scanned entry with:
    fields_needed=true    => Include (members are visible)
    functions_needed=false=> additionally blocklist all generated method
                             wrappers (`{Name}_.+`; the hand-written `C_*`
                             wrappers are unaffected)
    functions_needed=true => non-blocklisted; with fields_needed=false the
                             builder derives `Opaque`
    both=false            => the builder blocklists the type entirely

With `--update-table`, the scanner rewrites `scanned_f(..)` call arguments
in type_bindings.rs 1:1 (same entry order), and keeps the verdict line
`// SCAN: <name> = <verdict>` in the SCAN comment block as evidence.
"""
import re
import sys
import json
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
TABLE = HERE.parent / "type_bindings.rs"
REPO = HERE.parent.parent.parent  # tools -> build_support -> skia-bindings -> repo
SCAN_DIRS = [REPO / "skia-safe" / "src", REPO / "skia-bindings" / "src"]

SCAN_BEGIN = "// ---- SCAN BEGIN (generated by tools/scan_type_usage.py) ----"
SCAN_END = "// ---- SCAN END ----"


def table_includes():
    text = TABLE.read_text()
    names = []
    for m in re.finditer(r'scanned_f\(\s*\n?\s*"([^"]+)"', text):
        if m.group(1) not in names:
            names.append(m.group(1))
    return names


def load_corpus():
    parts = []
    for base in SCAN_DIRS:
        if not base.exists():
            continue
        for path in base.rglob("*.rs"):
            try:
                parts.append(path.read_text(errors="ignore"))
            except OSError:
                pass
    return "\n".join(parts)


def rust_names(name):
    """All plausible Rust-side spellings of a C++ table name."""
    forms = set()
    short = name.rsplit("::", 1)[-1]
    if len(short) >= 4:
        forms.add(short)
    if len(name) >= 4:
        forms.add(name)
    flat = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if len(flat) >= 4:
        forms.add(flat)
    return sorted(forms)


def classify(forms, blob):
    fields = False
    func = False
    native_field = False
    qualified = any("::" in f for f in forms)
    for form in forms:
        esc = re.escape(form)
        # Struct literals must match the qualified spelling: the bare last
        # name component also matches unrelated types with the same short
        # name (e.g. `skhdr::Metadata` vs `skia_safe::pdf::Metadata { .. }`
        # in examples).
        literal_ok = "::" in form or not qualified
        if (
            re.search(rf"\b{esc}\s*\.\s*[a-z_][a-z0-9_]*", blob)
            or (literal_ok and re.search(rf"\b{esc}\s*\{{", blob))
            or re.search(rf"native_transmutable![^;]*\b{esc}\b", blob)
        ):
            fields = True
        if re.search(rf"native(_mut)?\(\)\s*\.\s*{esc}\b", blob):
            native_field = True
            fields = True
        if re.search(rf"\b{esc}_[a-z][a-z0-9_]*\s*\(", blob) or re.search(
            rf"\b{esc}\s*::\s*[a-z_][a-z0-9_]*\s*\(", blob
        ):
            func = True
    return fields, func, native_field


def update_table(annotations):
    path = HERE.parent / "type_bindings.rs"
    text = path.read_text()

    # Rewrite the scanned_f() call arguments 1:1, in table order, from the
    # fresh scan verdicts.
    verdicts = {}
    for annotation in annotations:
        name, verdict = annotation.split(" = ", 1)
        name = name.replace("// SCAN: ", "")
        verdicts[name] = verdict
    index = 0

    def rewrite(m):
        nonlocal index
        name = m.group(1)
        v = verdicts.get(name, "")
        fields_needed = "fields" in v
        functions_needed = "functions" in v
        index += 1
        return m.group(0).replace(
            f'scanned_f(\n    "{name}"',
            f'scanned_f(\n    "{name}"',
        )

    # Simple, safe approach: replace each scanned_f(name, true/false, true/false, ...)
    # arg pair individually.
    def rewrite_entry(m):
        name = m.group(1)
        v = verdicts.get(name)
        if v is None:
            return m.group(0)
        fields_needed = "fields" in v.split("+")
        functions_needed = "functions" in v.split("+")
        return (
            f'scanned_f("{name}", {str(fields_needed).lower()}, '
            f"{str(functions_needed).lower()},{m.group(2)})"
        )

    text = re.sub(
        r'scanned_f\(\s*"([^"]+)"(.)*?\)\s*,\n',
        rewrite_entry,
        text,
    )

    block = SCAN_BEGIN + "\n" + "\n".join(annotations) + "\n" + SCAN_END
    if SCAN_BEGIN in text:
        start = text.index(SCAN_BEGIN)
        end = text.index(SCAN_END) + len(SCAN_END)
        text = text[:start] + block + text[end:]
    else:
        marker = "pub(crate) const TYPES"
        idx = text.index(marker)
        text = text[:idx] + block + "\n\n" + text[idx:]
    path.write_text(text)
    return len(annotations)


def main():
    verbose = "--verbose" in sys.argv
    do_update = "--update-table" in sys.argv

    blob = load_corpus()
    print(f"corpus: {len(blob) // 1024} KiB")

    names = table_includes()
    print(f"{len(names)} scanned entries")

    counts = defaultdict(int)
    annotations = []
    for name in names:
        forms = rust_names(name)
        fields, func, native = classify(forms, blob)
        props = set()
        if fields:
            props.add("fields")
        if native:
            props.add("native-field")
        if func:
            props.add("functions")
        verdict = "+".join(sorted(props)) if props else "none"
        counts[verdict] += 1
        annotations.append(f"// SCAN: {name} = {verdict}")
        if verbose:
            print(f"{name:55s} {verdict}")

    print("\nverdict histogram:")
    for k in sorted(counts):
        print(f"  {k:15s} {counts[k]}")

    (HERE / "scan-results.json").write_text(
        json.dumps({a.split(" = ")[0].replace("// SCAN: ", ""): a.split(" = ")[1] for a in annotations}, indent=2)
    )
    print("wrote scan-results.json")

    if do_update:
        n = update_table(annotations)
        print(f"updated SCAN block in type_bindings.rs ({n} annotations)")


if __name__ == "__main__":
    main()
