#!/usr/bin/env python3
"""--functions mode helper: for each fields-only Include entry, harvest the
generated function names touching that type from the latest generated
bindings.rs and emit a table patch of `function_blocklists` entries.

Harvests `pub fn <Name>_<method>(` / `pub unsafe fn <Name>_<method>(` from
the generated file, then writes per-type blocklist patterns
(`<Name>_<method>.*`) into the type's table entry.

Types that appear ONLY in function signatures (func-only/none verdicts)
are excluded from this pass — they are already Opaque/Excluded, and their
wrappers were written by hand in skia-bindings/src/*.cpp (never generated
from the headers, so the harvest below does not see them).
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent
TABLE = HERE.parent / "type_bindings.rs"
SCAN_JSON = HERE / "scan-results.json"


def find_bindings_rs():
    candidates = sorted(
        (REPO / "target" / "debug" / "build").glob("*/out/skia/bindings.rs"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise SystemExit("no generated bindings.rs found; run a build first")
    return candidates[0]


def main():
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "scan-results.json"
    results = json.loads(json_path.read_text())

    bindings = max(
        (REPO / "target" / "debug" / "build").glob("*/out/skia/bindings.rs"),
        key=lambda p: p.stat().st_mtime,
    ).read_text(errors="ignore")

    # All generated top-level function names.
    fn_names = set(re.findall(r"pub (?:unsafe )?fn ([A-Za-z_][A-Za-z0-9_]*)\(", bindings))

    # For each fields-only entry (has 'fields' but no 'functions' verdict),
    # harvest `<Name>_<method>` names and turn them into blocklist patterns.
    patterns = {}
    # Verdict values in scan-results.json are strings ("fields") — treat
    # them as single-element lists for uniform membership checks.
    for name, props in results.items():
        fields_used = "fields" in (props if isinstance(props, list) else [props])
        functions_used = "functions" in (props if isinstance(props, list) else [props])
        if not fields_used or functions_used:
            continue
        short = name.rsplit("::", 1)[-1]
        prefix = short + "_"
        hits = sorted(n for n in fn_names if n.startswith(prefix))
        if hits:
            patterns[name] = [re.escape(h) for h in hits]

    print(f"{len(patterns)} fields-only types with generated functions")
    total = sum(len(v) for v in patterns.values())
    print(f"{total} function blocklist patterns total")

    # Append them into the SCAN block as SCAN-FN annotations; a follow-up
    # pass (or manual edit) moves them into the entries' function_blocklists.
    table = HERE.parent / "type_bindings.rs"
    text = table.read_text()
    lines = []
    for name, pats in sorted(patterns.items()):
        lines.append(
            f"// SCAN-FN: {name} => [{', '.join(pats)}]"
        )
    block = (
        "// ---- SCAN-FN BEGIN (generated by tools/scan_type_usage.py --functions) ----\n"
        + "\n".join(lines)
        + "\n// ---- SCAN-FN END ----"
    )
    begin = "// ---- SCAN-FN BEGIN"
    if begin in text:
        s = text.index(begin)
        e = text.index("// ---- SCAN-FN END") + len("// ---- SCAN-FN END")
        text = text[:s] + block + text[e:]
    else:
        marker = "// ---- SCAN END ----"
        idx = text.index(marker) + len(marker)
        text = text[:idx] + "\n" + block + text[idx:]
    table.write_text(text)
    print(f"updated SCAN-FN block in type_bindings.rs ({len(patterns)} annotations)")


if __name__ == "__main__":
    main()